version: '3.8'

services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: agent-recall-db
    environment:
      POSTGRES_DB: agent_recall
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: agent_recall_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
